name: Update README with Random Meme

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script to update README
        run: python ./meme.py

      - name: Commit and push if changed
        run: |
          git config --global user.email "swaritpandey@gmail.com"
          git config --global user.name "Swarit"
          git diff
          git commit -am "Update README with random meme" || echo "No changes to commit"
          git push
